apiVersion: v1
appVersion: "6.8.5"
description: A Helm chart for MemSQL Operator
name: memsql-operator
version: 0.1.0
maintainers:
- name: ariefrahmansyah
  email: ariefrahmansyah@hotmail.com
keywords:
- operator
- memsql
