---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "memsql-operator-chart.fullname" . }}
  labels:
{{ include "memsql-operator-chart.labels" . | indent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "memsql-operator-chart.fullname" . }}
  labels:
{{ include "memsql-operator-chart.labels" . | indent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
    verbs:
      - '*'
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - memsql.com
    resources:
      - '*'
    verbs:
      - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "memsql-operator-chart.fullname" . }}
  labels:
{{ include "memsql-operator-chart.labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "memsql-operator-chart.fullname" . }}
roleRef:
  kind: Role
  name: {{ include "memsql-operator-chart.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
